version: '2'

services:
  server:
    container_name: confapp_server
    build: ./
    command: ./confapp
    ports:
      - 22952:22952
    depends_on:
      - postgres

  postgres:
    container_name: confapp_postgres
    image: postgres:alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always